Repository MarcoPoggi/rativity-api, pull requests merged in 2023-01, with the labels that each got.

#15 #11 - Setup Database
  package-lock.json
  package.json
  src/database/config.js
  src/database/init.js
  src/index.js
Labels: feature

#16 #T18/T19 Set file tree
  package-lock.json
  src/controllers/.keep
  src/database/init.js
  src/middlewares/.keep
  src/models/.keep
  src/routes/.keep
Labels: bug, documentation

#17 T33 - Add task runner
  config/database_config.js
  lib/task_runner.js
  lib/tasks/create_database.js
  package.json
  src/database/database.js
  src/database/init.js
  src/index.js
Labels: bug, good first issue

#18 #T20/22/33
  config/database_config.js
  src/database/database.js
  src/database/initialize_models.js
  src/index.js
  src/models/associations/.keep
  src/models/task.js
  src/models/task_list.js
  src/models/user.js
Labels: bug, feature

#20 #T23 Create category model
  src/models/category.js
Labels: feature

#19 #T21 Task list model created
  src/models/task_list.js
Labels: feature

#21 #T25-Validate-user-model
  src/models/user.js
Labels: feature
